#############################################################################
# Makefile for building: libvisualization.a
# Generated by qmake (2.01a) (Qt 4.8.3) on: ?? ???. 20 10:01:24 2013
# Project:  geom-visualization.pro
# Template: lib
# Command: /usr/bin/qmake -o Makefile geom-visualization.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -fPIC -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -std=c++0x -Wall -O2 -fPIC -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -Iheaders -Isrc -I/usr/X11R6/include -I.
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = bin/

####### Files

SOURCES       = src/io/primitives.cpp \
		src/visualization/drawer_impl.cpp \
		src/visualization/printer_impl.cpp \
		src/visualization/main_window.cpp \
		src/visualization/visualization.cpp \
		src/visualization/draw_util.cpp 
OBJECTS       = bin/primitives.o \
		bin/drawer_impl.o \
		bin/printer_impl.o \
		bin/main_window.o \
		bin/visualization.o \
		bin/draw_util.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/static.prf \
		/usr/share/qt4/mkspecs/features/staticlib.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		geom-visualization.pro
QMAKE_TARGET  = visualization
DESTDIR       = 
TARGET        = libvisualization.a

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c -include bin/visualization $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c -include bin/visualization $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c -include bin/visualization $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c -include bin/visualization $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c -include bin/visualization $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET) 

staticlib: $(TARGET)

$(TARGET):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGET)
	$(AR) $(TARGET) $(OBJECTS)


Makefile: geom-visualization.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/static.prf \
		/usr/share/qt4/mkspecs/features/staticlib.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile geom-visualization.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/static.prf:
/usr/share/qt4/mkspecs/features/staticlib.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile geom-visualization.pro

dist: 
	@$(CHK_DIR_EXISTS) bin/visualization1.0.0 || $(MKDIR) bin/visualization1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) bin/visualization1.0.0/ && $(COPY_FILE) --parents src/stdafx.h headers/common/range.h headers/io/point.h headers/io/range.h headers/io/rectangle.h headers/io/segment.h headers/io/vector.h headers/visualization/draw_util.h headers/visualization/viewer.h src/visualization/drawer_impl.h src/visualization/main_window.h src/visualization/printer_impl.h headers/geom/primitives/contour.h headers/geom/primitives/point.h headers/geom/primitives/range.h headers/geom/primitives/rectangle.h headers/geom/primitives/segment.h headers/geom/primitives/vector.h bin/visualization1.0.0/ && $(COPY_FILE) --parents src/io/primitives.cpp src/visualization/drawer_impl.cpp src/visualization/printer_impl.cpp src/visualization/main_window.cpp src/visualization/visualization.cpp src/visualization/draw_util.cpp bin/visualization1.0.0/ && (cd `dirname bin/visualization1.0.0` && $(TAR) visualization1.0.0.tar visualization1.0.0 && $(COMPRESS) visualization1.0.0.tar) && $(MOVE) `dirname bin/visualization1.0.0`/visualization1.0.0.tar.gz . && $(DEL_FILE) -r bin/visualization1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) bin/visualization.gch/c bin/visualization.gch/c++
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


###### Prefix headers
bin/visualization.gch/c: src/stdafx.h 
	@$(CHK_DIR_EXISTS) bin/visualization.gch/ || $(MKDIR) bin/visualization.gch/ 
	$(CC) $(CFLAGS) $(INCPATH) -x c-header -c src/stdafx.h -o bin/visualization.gch/c

bin/visualization.gch/c++: src/stdafx.h 
	@$(CHK_DIR_EXISTS) bin/visualization.gch/ || $(MKDIR) bin/visualization.gch/ 
	$(CXX) $(CXXFLAGS) $(INCPATH) -x c++-header -c src/stdafx.h -o bin/visualization.gch/c++

check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

bin/primitives.o: src/io/primitives.cpp bin/visualization.gch/c++
	$(CXX) -c -include bin/visualization $(CXXFLAGS) $(INCPATH) -o bin/primitives.o src/io/primitives.cpp

bin/drawer_impl.o: src/visualization/drawer_impl.cpp src/visualization/drawer_impl.h \
		bin/visualization.gch/c++
	$(CXX) -c -include bin/visualization $(CXXFLAGS) $(INCPATH) -o bin/drawer_impl.o src/visualization/drawer_impl.cpp

bin/printer_impl.o: src/visualization/printer_impl.cpp src/stdafx.h \
		src/visualization/printer_impl.h \
		bin/visualization.gch/c++
	$(CXX) -c -include bin/visualization $(CXXFLAGS) $(INCPATH) -o bin/printer_impl.o src/visualization/printer_impl.cpp

bin/main_window.o: src/visualization/main_window.cpp src/stdafx.h \
		src/visualization/main_window.h \
		src/visualization/drawer_impl.h \
		src/visualization/printer_impl.h \
		bin/visualization.gch/c++
	$(CXX) -c -include bin/visualization $(CXXFLAGS) $(INCPATH) -o bin/main_window.o src/visualization/main_window.cpp

bin/visualization.o: src/visualization/visualization.cpp src/stdafx.h \
		src/visualization/main_window.h \
		src/visualization/drawer_impl.h \
		bin/visualization.gch/c++
	$(CXX) -c -include bin/visualization $(CXXFLAGS) $(INCPATH) -o bin/visualization.o src/visualization/visualization.cpp

bin/draw_util.o: src/visualization/draw_util.cpp src/stdafx.h \
		bin/visualization.gch/c++
	$(CXX) -c -include bin/visualization $(CXXFLAGS) $(INCPATH) -o bin/draw_util.o src/visualization/draw_util.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

